# Generated by Django 3.1.3 on 2020-11-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201007_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
