version: '3.7'

services:
#  db:
#     image: mysql:8
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_DATABASE='mydatabase'
#       - MYSQL_USER='root'
#       - MYSQL_PASSWORD='some_password'
#       - MYSQL_ROOT_PASSWORD='some_password'
#       - MYSQL_HOST=''
#     volumes:
#       - /tmp/app/mysqld:/var/run/mysqld
#       - ./db:/var/lib/mysql

  app:
    build:
      context: .
    volumes: 
      - static_data:/vol/web
    environment: 
      - SECRETE_KEY=samplesecretekey123
      - ALLOWED_HOSTS=127.0.0.1,localhost
  poxy:
    build: 
      context: ./proxy
    volumes: 
      - static_data:/vol/static
    ports: 
      - "8080:8080"
    depends_on: 
      - app
volumes: 
  static_data:
