version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password1
      POSTGRES_USER: root
      POSTGRES_DB: employeedb

  app:
    build:
      context: .
    volumes: 
      - static_data:/vol/web
    environment: 
      - SECRETE_KEY=samplesecretekey123
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DJANGO_SUPERUSER_EMAIL="admin@gmail.com"
      - DJANGO_SUPERUSER_PASSWORD="keypass"
  poxy:
    build: 
      context: ./nginx
    volumes: 
      - static_data:/vol/static
    ports: 
      - "8080:8080"
    depends_on: 
      - app
volumes: 
  static_data:
