version: '3.7'

services: 
  app:
    build:
      context: .
    volumes: 
      - static_data:/vol/web
    environment: 
      - SECRETE_KEY=samplesecretekey123
      - ALLOWED_HOSTS=127.0.0.1,localhost
  poxy:
    build: 
      context: ./proxy
    volumes: 
      - static_data:/vol/static
    ports: 
      - "8080:8080"
    depends_on: 
      - app
volumes: 
  static_data:
