# Generated by Django 3.1.2 on 2020-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20201121_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='soburdinate',
            field=models.ManyToManyField(null=True, related_name='subordinates', to='employees.Employee'),
        ),
    ]
