# Generated by Django 3.1.2 on 2020-11-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20201122_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='soburdinate',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='soburdinate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='employees.employee'),
        ),
    ]
