# Generated by Django 3.1.2 on 2020-11-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20201122_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='employee_profile',
            new_name='Supervisor',
        ),
    ]
