# Generated by Django 3.1.3 on 2020-11-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20201122_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files')),
            ],
        ),
    ]
