# Generated by Django 3.1.3 on 2020-11-24 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_excelfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfiles',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 5, 28, 54, 551619)),
        ),
    ]
