# Generated by Django 3.1.3 on 2020-11-24 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_excelfiles_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfiles',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 6, 45, 18, 466569)),
        ),
    ]
