# Generated by Django 3.1.3 on 2020-11-25 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20201124_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 17, 21, 31, 431923)),
        ),
    ]
