# Generated by Django 3.1.3 on 2020-11-25 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20201124_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='excelfiles',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 17, 30, 32, 761685)),
        ),
    ]
